### ISSUE TITLE
ArrayExpression has no attribute name

### ISSUE THREAD

**Issue by Thomas-P** [escomplex/escomplex#66]
Is it right, that the ArrayExpression operands is at all time `<anonymous>`?

The EsTree Syntax says that there is not an attribute 'name' on this object.
see [Spec](https://github.com/estree/estree/blob/master/spec.md)

**Comment by jared-stilwell** [comment]
Your observation is correct. The syntax definition for `ArrayExpression` nodes always includes an `operands` value set to `"<anonymous>"`. This seems intentional in order to get the Halstead metrics to work out correctly, however I think a better implementation might be to include the node's `elements` array as the list of operands instead.

I intend to give this a bit more thought before pushing changes to improve this. I'm curious to get your feedback in the meantime.
